from modules.preprocessor import process as preprocess
from modules.intent_detector import process as detect_intent
from modules.classifier import process as classify
from modules.defense import process as defend


def verify_llm_output(text: str, history=None):
    """
    This module re-checks the RESPONSE generated by the LLM.
    It ensures the AI itself is not producing unsafe or malicious content.
    """

    history = history or []

    # 🔹 Step 1 — Preprocess LLM response
    p = preprocess(text, history)

    # 🔹 Step 2 — Detect intent in the AI response
    i = detect_intent(p["clean_text"], history)

    # 🔹 Step 3 — Classify risk using ML model
    c = classify(i)

    # 🔹 Step 4 — Apply defense policy
    d = defend(p["clean_text"], c)

    return {
        "classification": c["risk"],      # benign / suspicious / malicious
        "action": d["action"],            # allow / warn / block
        "safe_output": d["safe_prompt"],  # filtered or safe version
        "note": d.get("note")             # explanation if modified
    }
